name: Manual KSU Build

on: workflow_dispatch

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-22.04
    env:
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-elf- O=out"
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt install bc bison build-essential curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick jq lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lunzip lzop pngcrush python-is-python3 python3 rr rsync schedtool simg2img squashfs-tools virtualenv xattr xmlstarlet xsltproc xz-utils zip zlib1g-dev -y

    - name: Get Toolchain
      run: |
        wget https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/aarch64-elf/gcc-linaro-7.5.0-2019.12-i686_aarch64-elf.tar.xz --no-check-certificate
        tar xf gcc-linaro-7.5.0-2019.12-i686_aarch64-elf.tar.xz

    - name: Checkout KernelSU
      run: |
        wget https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh
        bash setup.sh --cleanup
        rm -rf setup.sh
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next

    - name: Set Date of Build
      id: dob
      run: |
        echo "TIME=$(TZ=UTC-8 date +%d%m%y )" >> $GITHUB_OUTPUT

    - name: Build Kernel
      run: |
        export PATH=$(pwd)/gcc-linaro-7.5.0-2019.12-i686_aarch64-elf/bin/:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        LLVM=1 
        LLVM_IAS=1 
      	HOSTCFLAGS="-fuse-ld=lld -Wno-unused-command-line-argument" 
      	CROSS_COMPILE=${CLANG_ROOTDIR}/bin/aarch64-linux-gnu- 
      	CROSS_COMPILE_ARM32=${CLANG_ROOTDIR}/bin/arm-linux-gnueabi- 

    - name: Upload Kernel
      uses: actions/upload-artifact@v3
      with:
        name: image-${{ steps.dob.outputs.TIME }}
        path: "image-*.img"
